WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
CheckWordInstanceExists: config.actions.OfficeAutomation.Word.CheckWordInstanceExists.CheckWordInstanceExists
WordAppendDataTable: config.actions.OfficeAutomation.Word.WordAppendDataTables.WordAppendDataTable
WordCloseDocument: config.actions.OfficeAutomation.Word.WordCloseDocument.WordCloseDocument
WordAddDocument: config.actions.OfficeAutomation.Word.WordAddDocument.WordAddDocument
WordAppendImage: config.actions.OfficeAutomation.Word.WordAppendImage.WordAppendImage
WordAppendText: config.actions.OfficeAutomation.Word.WordAppendText.WordAppendText
WordCursorDeleteEnter: config.actions.OfficeAutomation.Word.WordCursorDeleteEnter.WordCursorDeleteEnter
WordCursorInsertEnter: config.actions.OfficeAutomation.Word.WordCursorInsertEnter.WordCursorInsertEnter