WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
CheckImageExists: config.actions.DesktopAutomation.Image.CheckImageExists.CheckImageExists
SearchImagePoint: config.actions.DesktopAutomation.Image.SearchImagePoint.SearchImagePoint
WaitForImage: config.actions.DesktopAutomation.Image.WaitForImage.WaitForImage
CheckTextExists: config.actions.DesktopAutomation.Text.CheckTextExists.CheckTextExists
GetElementByText: config.actions.DesktopAutomation.Text.GetElementByText.GetElementByText
GetTextValue: config.actions.DesktopAutomation.Text.GetTextValue.GetTextValue
MouseClickText: config.actions.DesktopAutomation.Text.MouseClickText.MouseClickText
MouseMoveText: config.actions.DesktopAutomation.Text.MouseMoveText.MouseMoveText
GetAppointPage: config.actions.FileOperation.Pdf.GetAppointPage.GetAppointPage
GetPDFAllPicture: config.actions.FileOperation.Pdf.GetPDFAllPicture.GetPDFAllPicture
GetPDFAppointPicture: config.actions.FileOperation.Pdf.GetPDFAppointPicture.GetPDFAppointPicture
GetPDFMerge: config.actions.FileOperation.Pdf.GetPDFMerge.GetPDFMerge
GetPDFPageCount: config.actions.FileOperation.Pdf.GetPDFPageCount.GetPDFPageCount
PDFSetPwd: config.actions.FileOperation.Pdf.PDFSetPwd.PDFSetPwd
PDFSplitPage: config.actions.FileOperation.Pdf.PDFSplitPage.PDFSplitPage
PDFToPicture: config.actions.FileOperation.Pdf.PDFToPicture.PDFToPicture