WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
WebBrowserActiveTab: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserActiveTab.WebBrowserActiveTab
WebBrowserBind: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserBind.WebBrowserBind
WebBrowserCreate: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserCreate.WebBrowserCreate
WebBrowserCloseTab: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserCloseTab.WebBrowserCloseTab
WebBrowserGetHtml: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGetHtml.WebBrowserGetHtml
WebBrowserGetStatus: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGetStatus.WebBrowserGetStatus
WebBrowserGetTitle: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGetTitle.WebBrowserGetTitle
WebBrowserGetUrl: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGetUrl.WebBrowserGetUrl
WebBrowserGoBack: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGoBack.WebBrowserGoBack
WebBrowserGoForward: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGoForward.WebBrowserGoForward
WebBrowserNewTab: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserNewTab.WebBrowserNewTab
WebBrowserReload: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserReload.WebBrowserReload
WebBrowserRunJs: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserRunJs.WebBrowserRunJs
WebBrowserTakeShot: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserTakeShot.WebBrowserTakeShot
