WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
Sout: config.actions.DesktopAutomation.Screen.Sout.Sout
GetElementHandle: config.actions.DesktopAutomation.Screen.GetElementHandle.GetElementHandle
CheckElementExists: config.actions.DesktopAutomation.Screen.CheckElementExists.CheckElementExists
GetChildElement: config.actions.DesktopAutomation.Screen.GetChildElement.GetChildElement
GetParentElement: config.actions.DesktopAutomation.Screen.GetParentElement.GetParentElement
GetElementCheck: config.actions.DesktopAutomation.Screen.GetElementCheck.GetElementCheck
SetElementCheck: config.actions.DesktopAutomation.Screen.SetElementCheck.SetElementCheck
GetElementSelect: config.actions.DesktopAutomation.Screen.GetElementSelect.GetElementSelect
SetElementSelect: config.actions.DesktopAutomation.Screen.SetElementSelect.SetElementSelect
GetElementAttribute: config.actions.DesktopAutomation.Screen.GetElementAttribute.GetElementAttribute
SetElementAttribute: config.actions.DesktopAutomation.Screen.SetElementAttribute.SetElementAttribute
GetElementValue: config.actions.DesktopAutomation.Screen.GetElementValue.GetElementValue
SetElementValue: config.actions.DesktopAutomation.Screen.SetElementValue.SetElementValue
GetElementRect: config.actions.DesktopAutomation.Screen.GetElementRect.GetElementRect
ElementTakeShot: config.actions.DesktopAutomation.Screen.ElementTakeShot.ElementTakeShot
WaitForElement: config.actions.DesktopAutomation.Screen.WaitForElement.WaitForElement
GetElementTable: config.actions.DesktopAutomation.Screen.GetElementTable.GetElementTable
ScreenShot: config.actions.DesktopAutomation.Screen.ScreenShot.ScreenShot
GetBatchData: config.actions.DesktopAutomation.Screen.GetBatchData.GetBatchData