WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
ExcelOpenWorkbook: config.actions.OfficeAutomation.Excel.ExcelOpenWorkbook.ExcelOpenWorkbook
ExcelSave: config.actions.OfficeAutomation.Excel.ExcelSave.ExcelSave
ExcelSaveAs: config.actions.OfficeAutomation.Excel.ExcelSaveAs.ExcelSaveAs
ExcelCloseWorkSheet: config.actions.OfficeAutomation.Excel.ExcelCloseWorkSheet.ExcelCloseWorkSheet
ExcelSelectData: config.actions.OfficeAutomation.Excel.ExcelSelectData.ExcelSelectData
ExcelReadCell: config.actions.OfficeAutomation.Excel.ExcelReadCell.ExcelReadCell
ExcelSetCell: config.actions.OfficeAutomation.Excel.ExcelSetCell.ExcelSetCell
ExcelGetRange: config.actions.OfficeAutomation.Excel.ExcelGetRange.ExcelGetRange
ExcelSetSelectArea: config.actions.OfficeAutomation.Excel.ExcelSetSelectArea.ExcelSetSelectArea
ExcelClearArea: config.actions.OfficeAutomation.Excel.ExcelClearArea.ExcelClearArea
ExcelDeleteArea: config.actions.OfficeAutomation.Excel.ExcelDeleteArea.ExcelDeleteArea
ExcelGetRowData: config.actions.OfficeAutomation.Excel.ExcelGetRowData.ExcelGetRowData
ExcelSetRow: config.actions.OfficeAutomation.Excel.ExcelSetRow.ExcelSetRow
ExcelInsertRow: config.actions.OfficeAutomation.Excel.ExcelInsertRow.ExcelInsertRow
ExcelDeleteRow: config.actions.OfficeAutomation.Excel.ExcelDeleteRow.ExcelDeleteRow