WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
ExcelAddWorksheet: config.actions.OfficeAutomation.Excel.ExcelAddWorksheet.ExcelAddWorksheet
ExcelBackgroundColor: config.actions.OfficeAutomation.Excel.ExcelBackgroundColor.ExcelBackgroundColor
ExcelColumnWidth: config.actions.OfficeAutomation.Excel.ExcelColumnWidth.ExcelColumnWidth
ExcelDeleteColumn: config.actions.OfficeAutomation.Excel.ExcelDeleteColumn.ExcelDeleteColumn
ExcelFontColor: config.actions.OfficeAutomation.Excel.ExcelFontColor.ExcelFontColor
ExcelGetAllWorkSheet: config.actions.OfficeAutomation.Excel.ExcelGetAllWorkSheet.ExcelGetAllWorkSheet
ExcelGetColumnData: config.actions.OfficeAutomation.Excel.ExcelGetColumnData.ExcelGetColumnData
ExcelGetColumnNumber: config.actions.OfficeAutomation.Excel.ExcelGetColumnNumber.ExcelGetColumnNumber
ExcelGetFontColor: config.actions.OfficeAutomation.Excel.ExcelGetFontColor.ExcelGetFontColor
ExcelGetRowNumber: config.actions.OfficeAutomation.Excel.ExcelGetRowNumber.ExcelGetRowNumber
ExcelGetWorkSheet: config.actions.OfficeAutomation.Excel.ExcelGetWorkSheet.ExcelGetWorkSheet
ExcelInsertColumn: config.actions.OfficeAutomation.Excel.ExcelInsertColumn.ExcelInsertColumn
ExcelMergeCell: config.actions.OfficeAutomation.Excel.ExcelMergeCell.ExcelMergeCell
ExcelRenameWorkSheet: config.actions.OfficeAutomation.Excel.ExcelRenameWorkSheet.ExcelRenameWorkSheet
ExcelRowHeight: config.actions.OfficeAutomation.Excel.ExcelRowHeight.ExcelRowHeight
ExcelSetColumn: config.actions.OfficeAutomation.Excel.ExcelSetColumn.ExcelSetColumn
CheckFileExists: config.actions.FileOperation.common.CheckFileExists.CheckFileExists
CheckFolderExists: config.actions.FileOperation.common.CheckFolderExists.CheckFolderExists
CreateFolder: config.actions.FileOperation.common.CreateFolder.CreateFolder
DeleteFile: config.actions.FileOperation.common.DeleteFile.DeleteFile
DeleteFolder: config.actions.FileOperation.common.DeleteFolder.DeleteFolder
GetFileExtension: config.actions.FileOperation.common.GetFileExtension.GetFileExtension
GetFileName: config.actions.FileOperation.common.GetFileName.GetFileName
GetFileSize: config.actions.FileOperation.common.GetFileSize.GetFileSize
GetFolderSize: config.actions.FileOperation.common.GetFolderSize.GetFolderSize
GetParentFile: config.actions.FileOperation.common.GetParentFile.GetParentFile
MoveFile: config.actions.FileOperation.common.MoveFile.MoveFile
MoveFolder: config.actions.FileOperation.common.MoveFolder.MoveFolder
ReadTextFile: config.actions.FileOperation.common.ReadTextFile.ReadTextFile
RenameFile: config.actions.FileOperation.common.RenameFile.RenameFile
WriteTextFile: config.actions.FileOperation.common.WriteTextFile.WriteTextFile