WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
OpenCSV: config.actions.FileOperation.csv.OpenCSV.OpenCSV
WaitForFileToExist: config.actions.FileOperation.common.WaitForFileToExist.WaitForFileToExist
ExtractFile: config.actions.FileOperation.common.ExtractFile.ExtractFile
GetFiles: config.actions.FileOperation.common.GetFiles.GetFiles
GetFolders: config.actions.FileOperation.common.GetFolders.GetFolders
RenameFolder: config.actions.FileOperation.common.RenameFolder.RenameFolder
ZipFile: config.actions.FileOperation.common.ZipFile.ZipFile
ZipFolder: config.actions.FileOperation.common.ZipFolder.ZipFolder
GetSystemCatalogue: config.actions.SystemOperation.System.GetSystemCatalogue.GetSystemCatalogue
GetSystemTemporary: config.actions.SystemOperation.System.GetSystemTemporary.GetSystemTemporary
GetSystemUser: config.actions.SystemOperation.System.GetSystemUser.GetSystemUser
SystemAction: config.actions.SystemOperation.System.SystemAction.SystemAction
RunPowershell: config.actions.SystemOperation.System.RunPowershell.RunPowershell
RunScript: config.actions.SystemOperation.System.RunScript.RunScript