WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
CSV_open_document: config.actions.FileOperation.csv.CSV_open_document.CSVOpenDocument
detect_file_exist: config.actions.FileOperation.common.detect_file_exist.detect_file_exist
extract_file: config.actions.FileOperation.common.extract_file.extract_file
get_files_list: config.actions.FileOperation.common.get_files_list.get_files_list
get_folders_list: config.actions.FileOperation.common.get_folders_list.get_folders_list
rename_folder: config.actions.FileOperation.common.rename_folder.rename_folder
zip_file: config.actions.FileOperation.common.zip_file.zip_file
zip_folder: config.actions.FileOperation.common.zip_folder.zip_folder
get_system_catalogue: config.actions.SystemOperation.System.get_system_catalogue.get_system_catalogue
get_system_temporary: config.actions.SystemOperation.System.get_system_temporary.get_system_temporary
get_system_user: config.actions.SystemOperation.System.get_system_user.get_system_user
lock_screen: config.actions.SystemOperation.System.lock_screen.lock_screen
run_powershell: config.actions.SystemOperation.System.run_powershell.run_powershell
run_script: config.actions.SystemOperation.System.run_script.run_script