ExcelActivateSheet: config.actions.OfficeAutomation.Excel.ExcelActivateSheet.ExcelActivateSheet
ExcelCopyWorkSheet: config.actions.OfficeAutomation.Excel.ExcelCopyWorkSheet.ExcelCopyWorkSheet
ExcelDeleteWorksheet: config.actions.OfficeAutomation.Excel.ExcelDeleteWorksheet.ExcelDeleteWorksheet
ExcelFlterData: config.actions.OfficeAutomation.Excel.ExcelFlterData.ExcelFlterData
ExcelGetRangeAsDT: config.actions.OfficeAutomation.Excel.ExcelGetRangeAsDT.ExcelGetRangeAsDT
ExcelRunMacro: config.actions.OfficeAutomation.Excel.ExcelRunMacro.ExcelRunMacro
ExcelWriteRange: config.actions.OfficeAutomation.Excel.ExcelWriteRange.ExcelWriteRange
ExcelOpenWorkbook: config.actions.OfficeAutomation.Excel.ExcelOpenWorkbook.ExcelOpenWorkbook
WordOpenDocument: config.actions.OfficeAutomation.Word.WordOpenDocument.WordOpenDocument
WordCopySelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordCopySelectTextContentCommnad.WordCopySelectTextContentCommnad
WordPasteSelectTextContentCommnad: config.actions.OfficeAutomation.Word.WordPasteSelectTextContentCommnad.WordPasteSelectTextContentCommnad
WordSelectAll: config.actions.OfficeAutomation.Word.WordSelectAll.WordSelectAll
StartProcess: config.actions.SystemOperation.Application.StartProcess.StartProcess
StopProgram: config.actions.SystemOperation.Application.StopProgram.StopProgram
MessageBox: config.actions.SystemOperation.Dialog.MessageBox.MessageBox
FileDialog: config.actions.SystemOperation.Dialog.FileDialog.FileDialog
FolderDialog: config.actions.SystemOperation.Dialog.FolderDialog.FolderDialog
InputDialog: config.actions.SystemOperation.Dialog.InputDialog.InputDialog
ClipboardSetText: config.actions.SystemOperation.Clipboard.ClipboardSetText.ClipboardSetText
Clipboard: config.actions.SystemOperation.Clipboard.Clipboard.Clipboard
PTSDrawText: config.actions.SystemOperation.PrintToScreen.PTSDrawText.PTSDrawText
PTSCleanText: config.actions.SystemOperation.PrintToScreen.PTSCleanText.PTSCleanText
LockWindows: config.actions.SystemOperation.LockScreen.LockWindows.LockWindows
TargetMouseClick: config.actions.MouseKeyboardAutomation.Mouse.TargetMouseClick.TargetMouseClick
SendTargetMouseMove: config.actions.MouseKeyboardAutomation.Mouse.SendTargetMouseMove.SendTargetMouseMove
SendMouseClick: config.actions.MouseKeyboardAutomation.Mouse.SendMouseClick.SendMouseClick
SendMouseMove: config.actions.MouseKeyboardAutomation.Mouse.SendMouseMove.SendMouseMove
GetMousePoint: config.actions.MouseKeyboardAutomation.Mouse.GetMousePoint.GetMousePoint
MouseDrag: config.actions.MouseKeyboardAutomation.Mouse.MouseDrag.MouseDrag
MouseWheel: config.actions.MouseKeyboardAutomation.Mouse.MouseWheel.MouseWheel
SendTargetKeys: config.actions.MouseKeyboardAutomation.KeyBoard.SendTargetKeys.SendTargetKeys
SendTargetAdvancedKeys: config.actions.MouseKeyboardAutomation.KeyBoard.SendTargetAdvancedKeys.SendTargetAdvancedKeys
SendKeys: config.actions.MouseKeyboardAutomation.KeyBoard.SendKeys.SendKeys
SendAdvancedKeys: config.actions.MouseKeyboardAutomation.KeyBoard.SendAdvancedKeys.SendAdvancedKeys
OpenCSV: config.actions.FileOperation.csv.OpenCSV.OpenCSV
WaitForFileToExist: config.actions.FileOperation.common.WaitForFileToExist.WaitForFileToExist
ExtractFile: config.actions.FileOperation.common.ExtractFile.ExtractFile
GetFiles: config.actions.FileOperation.common.GetFiles.GetFiles
GetFolders: config.actions.FileOperation.common.GetFolders.GetFolders
RenameFolder: config.actions.FileOperation.common.RenameFolder.RenameFolder
ZipFile: config.actions.FileOperation.common.ZipFile.ZipFile
ZipFolder: config.actions.FileOperation.common.ZipFolder.ZipFolder
GetSystemCatalogue: config.actions.SystemOperation.System.GetSystemCatalogue.GetSystemCatalogue
GetSystemTemporary: config.actions.SystemOperation.System.GetSystemTemporary.GetSystemTemporary
GetSystemUser: config.actions.SystemOperation.System.GetSystemUser.GetSystemUser
SystemAction: config.actions.SystemOperation.System.SystemAction.SystemAction
RunPowershell: config.actions.SystemOperation.System.RunPowershell.RunPowershell
RunScript: config.actions.SystemOperation.System.RunScript.RunScript
Sout: config.actions.DesktopAutomation.Screen.Sout.Sout
GetElementHandle: config.actions.DesktopAutomation.Screen.GetElementHandle.GetElementHandle
CheckElementExists: config.actions.DesktopAutomation.Screen.CheckElementExists.CheckElementExists
GetChildElement: config.actions.DesktopAutomation.Screen.GetChildElement.GetChildElement
GetParentElement: config.actions.DesktopAutomation.Screen.GetParentElement.GetParentElement
GetElementCheck: config.actions.DesktopAutomation.Screen.GetElementCheck.GetElementCheck
SetElementCheck: config.actions.DesktopAutomation.Screen.SetElementCheck.SetElementCheck
GetElementSelect: config.actions.DesktopAutomation.Screen.GetElementSelect.GetElementSelect
SetElementSelect: config.actions.DesktopAutomation.Screen.SetElementSelect.SetElementSelect
GetElementAttribute: config.actions.DesktopAutomation.Screen.GetElementAttribute.GetElementAttribute
SetElementAttribute: config.actions.DesktopAutomation.Screen.SetElementAttribute.SetElementAttribute
GetElementValue: config.actions.DesktopAutomation.Screen.GetElementValue.GetElementValue
SetElementValue: config.actions.DesktopAutomation.Screen.SetElementValue.SetElementValue
GetElementRect: config.actions.DesktopAutomation.Screen.GetElementRect.GetElementRect
ElementTakeShot: config.actions.DesktopAutomation.Screen.ElementTakeShot.ElementTakeShot
WaitForElement: config.actions.DesktopAutomation.Screen.WaitForElement.WaitForElement
GetElementTable: config.actions.DesktopAutomation.Screen.GetElementTable.GetElementTable
ScreenShot: config.actions.DesktopAutomation.Screen.ScreenShot.ScreenShot
GetBatchData: config.actions.DesktopAutomation.Screen.GetBatchData.GetBatchData
WebBrowserActiveTab: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserActiveTab.WebBrowserActiveTab
WebBrowserBind: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserBind.WebBrowserBind
WebBrowserCreate: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserCreate.WebBrowserCreate
WebBrowserCloseTab: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserCloseTab.WebBrowserCloseTab
WebBrowserGetHtml: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGetHtml.WebBrowserGetHtml
WebBrowserGetStatus: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGetStatus.WebBrowserGetStatus
WebBrowserGetTitle: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGetTitle.WebBrowserGetTitle
WebBrowserGetUrl: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGetUrl.WebBrowserGetUrl
WebBrowserGoBack: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGoBack.WebBrowserGoBack
WebBrowserGoForward: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserGoForward.WebBrowserGoForward
WebBrowserNewTab: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserNewTab.WebBrowserNewTab
WebBrowserReload: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserReload.WebBrowserReload
WebBrowserRunJs: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserRunJs.WebBrowserRunJs
WebBrowserTakeShot: config.actions.BrowserAutomation.BrowserAutomation.WebBrowserTakeShot.WebBrowserTakeShot
ExcelAddWorksheet: config.actions.OfficeAutomation.Excel.ExcelAddWorksheet.ExcelAddWorksheet
ExcelBackgroundColor: config.actions.OfficeAutomation.Excel.ExcelBackgroundColor.ExcelBackgroundColor
ExcelColumnWidth: config.actions.OfficeAutomation.Excel.ExcelColumnWidth.ExcelColumnWidth
ExcelDeleteColumn: config.actions.OfficeAutomation.Excel.ExcelDeleteColumn.ExcelDeleteColumn
ExcelFontColor: config.actions.OfficeAutomation.Excel.ExcelFontColor.ExcelFontColor
ExcelGetAllWorkSheet: config.actions.OfficeAutomation.Excel.ExcelGetAllWorkSheet.ExcelGetAllWorkSheet
ExcelGetColumnData: config.actions.OfficeAutomation.Excel.ExcelGetColumnData.ExcelGetColumnData
ExcelGetColumnNumber: config.actions.OfficeAutomation.Excel.ExcelGetColumnNumber.ExcelGetColumnNumber
ExcelGetFontColor: config.actions.OfficeAutomation.Excel.ExcelGetFontColor.ExcelGetFontColor
ExcelGetRowNumber: config.actions.OfficeAutomation.Excel.ExcelGetRowNumber.ExcelGetRowNumber
ExcelGetWorkSheet: config.actions.OfficeAutomation.Excel.ExcelGetWorkSheet.ExcelGetWorkSheet
ExcelInsertColumn: config.actions.OfficeAutomation.Excel.ExcelInsertColumn.ExcelInsertColumn
ExcelMergeCell: config.actions.OfficeAutomation.Excel.ExcelMergeCell.ExcelMergeCell
ExcelRenameWorkSheet: config.actions.OfficeAutomation.Excel.ExcelRenameWorkSheet.ExcelRenameWorkSheet
ExcelRowHeight: config.actions.OfficeAutomation.Excel.ExcelRowHeight.ExcelRowHeight
ExcelSetColumn: config.actions.OfficeAutomation.Excel.ExcelSetColumn.ExcelSetColumn
CheckFileExists: config.actions.FileOperation.common.CheckFileExists.CheckFileExists
CheckFolderExists: config.actions.FileOperation.common.CheckFolderExists.CheckFolderExists
CreateFolder: config.actions.FileOperation.common.CreateFolder.CreateFolder
DeleteFile: config.actions.FileOperation.common.DeleteFile.DeleteFile
DeleteFolder: config.actions.FileOperation.common.DeleteFolder.DeleteFolder
GetFileExtension: config.actions.FileOperation.common.GetFileExtension.GetFileExtension
GetFileName: config.actions.FileOperation.common.GetFileName.GetFileName
GetFileSize: config.actions.FileOperation.common.GetFileSize.GetFileSize
GetFolderSize: config.actions.FileOperation.common.GetFolderSize.GetFolderSize
GetParentFile: config.actions.FileOperation.common.GetParentFile.GetParentFile
MoveFile: config.actions.FileOperation.common.MoveFile.MoveFile
MoveFolder: config.actions.FileOperation.common.MoveFolder.MoveFolder
ReadTextFile: config.actions.FileOperation.common.ReadTextFile.ReadTextFile
RenameFile: config.actions.FileOperation.common.RenameFile.RenameFile
WriteTextFile: config.actions.FileOperation.common.WriteTextFile.WriteTextFile
