# 对外暴露的 id，用于将 group 引入 pipline
ref_id: "CodeExecutionGroup"

# group 名称
name: "CodeExecutionGroup"
# 对 group 的详细描述
description: "执行完整生成的代码，应当为完成任务的最后一步"
# group 要完成的任务
task: ""

# group 内包含的 agent
agents:
  - CodeExecutionAgent: "tbot/config/agent_net/agent/CodeExecutionAgent.yaml"
# 信息流开始的 agent
start_agent: CodeExecutionAgent
end_agent: CodeExecutionAgent

# 路由
routes:

# 最大执行步数
max_step: 100

# 执行上下文参数
params:
  - name: "code"
    type: "list"
  - name: "variables"
    type: "list"

# 执行上下文结果
results:

# group 场景下的 prompt
prompts:

# 初始化时需要的额外参数
initExtraParams:

# group 提供的工具
tools:

