# 对外暴露的 id，用于将 group 引入 pipline
ref_id: "TBotGroup"

# group 名称
name: "TBotGroup"
# 对 group 的详细描述
description: "生成完成任务的 tbot 代码"
# group 要完成的任务
task: ""

# group 内包含的 agent
agents:
  - WordOperationAgent: "tbot/config/agent_net/agent/WordOperationAgent.yaml"
  - WordDocumentAgent: "tbot/config/agent_net/agent/WordDocumentAgent.yaml"
  # - ExcelOperationAgent: "tbot/config/agent_net/agent/ExcelOperationAgent.yaml"
  - ManagerAgent: "tbot/config/agent_net/agent/ManagerAgent.yaml"

# 信息流开始的 agent
start_agent: ManagerAgent
end_agent: ManagerAgent

# 路由
routes:
  - source: "ManagerAgent"
    target: "WordOperationAgent"
    type: "message"
  # - source: "ManagerAgent"
  #   target: "ExcelOperationAgent"
  #   type: "message"
  - source: "WordOperationAgent"
    target: "ManagerAgent"
    type: "message"
  # - source: "ExcelOperationAgent"
  #   target: "ManagerAgent"
  #   type: "message"
  - source: "ManagerAgent"
    target: "WordDocumentAgent"
    type: "message"
  - source: "WordDocumentAgent"
    target: "ManagerAgent"
    type: "message"

block_flag:

# 执行上下文参数
params:
  - name: "task"
    type: "str"

# 执行上下文结果
results:
  - name: "code"
    type: "list"
  - name: "variables"
    type: "list"

# group 场景下的 prompt
prompts:

# 初始化时需要的额外参数
init_extra_params:

# group 提供的工具
tools:

children:

# 其他参数
ifLeaf: True
ifService: False
runtimeRevisionNumber: 1
ifKnowledgeable: True
historyNumber: 0
energy: 0
