# 对外暴露的 id，用于将 group 引入 pipline
ref_id: "TBotGroup"

# group 名称
name: "TBotGroup"
# 对 group 的详细描述
description: "生成完成任务的 tbot 代码"
# group 要完成的任务
task: ""

# group 内包含的 agent
agents:
  - WordFileManageAgent: "tbot/config/agent_net/agent/WordFileManageAgent.yaml"
  - WordTextContentAgent: "tbot/config/agent_net/agent/WordTextContentAgent.yaml"
  - WordFontSetAgent: "tbot/config/agent_net/agent/WordFontSetAgent.yaml"
  - WordDocumentAgent: "tbot/config/agent_net/agent/WordDocumentAgent.yaml"
  - ManagerAgent: "tbot/config/agent_net/agent/ManagerAgent.yaml"
  - WordMouseKeyboardAgent: "tbot/config/agent_net/agent/WordMouseKeyboardAgent.yaml"
  - EndAgent: "tbot/config/agent_net/agent/EndAgent.yaml"

# 信息流开始的 agent
start_agent: ManagerAgent

# 路由
routes:
  - source: "ManagerAgent"
    target: "WordFileManageAgent"
    type: "message"
  - source: "ManagerAgent"
    target: "WordTextContentAgent"
    type: "message"
  - source: "ManagerAgent"
    target: "WordMouseKeyboardAgent"
    type: "message"
  - source: "ManagerAgent"
    target: "WordFontSetAgent"
    type: "message"
  - source："ManagerAgent"
    target: "CodeExecutionGroup"
    type: "message"
  - source: "WordFileManageAgent"
    target: "ManagerAgent"
    type: "message"
  - source: "WordTextContentAgent"
    target: "ManagerAgent"
    type: "message"
  - source: "WordMouseKeyboardAgent"
    target: "ManagerAgent"
    type: "message"
  - source: "WordFontSetAgent"
    target: "ManagerAgent"
    type: "message"
  # - source: "ExcelOperationAgent"
  #   target: "ManagerAgent"
  #   type: "message"
  - source: "ManagerAgent"
    target: "WordDocumentAgent"
    type: "message"
  - source: "WordDocumentAgent"
    target: "ManagerAgent"
    type: "message"
  - source: "ManagerAgent"
    target: "EndAgent"
    type: "message"

# 最大执行步数
max_step: 100

# 执行上下文参数
params:
  - name: "task"
    type: "str"

# 执行上下文结果
results:
  - name: "code"
    type: "list"
  - name: "variables"
    type: "list"

# group 场景下的 prompt
prompts:

# 初始化时需要的额外参数
init_extra_params:

# group 提供的工具
tools:

children:

# 其他参数
ifLeaf: True
ifService: False
runtimeRevisionNumber: 1
ifKnowledgeable: True
historyNumber: 0
energy: 0
