args:
  element_name: ""
  check_rule1: "2"
  check_rule2: "1"
  click: "0"
  handle_obj: ""
  element_picture: ""
  pre_delay: 0
  post_delay: 0
  continue_when_error: False

rets:
  bool_obj: v_BRet