args:
  folder_path: "C:\\Users\\86188\\Desktop"
  target_path: "C:\\Users\\86188\\Desktop"
  zip_cipher: ""
  zip_name: "test"
  select_algorithm: 最快
  pre_delay: 0
  post_delay: 0
  continue_when_error: False

rets:
  zip_path: zipped_path_name1