name: WordAppendText

args:
  document: ""
  content: ""
  font: "宋体"
  size: 12
  bold: "NO"
  italic: "NO"
  underline: "NO"
  pre_delay: 0
  post_delay: 0
  continue_when_error: False

variables:
  - document