# pipline 名称
name: "HelpfulAgent"

# pipline 详细描述
description: "获取 word 文档信息并写入 excel"

# pipline 所执行的任务
task: ""

# 为了完成任务的计划，通过调用 group 完成任务
group_pipline:
  - TBotGroup: "tbot/config/agent_net/group/TBotGroup.yaml"
  - CodeExecutionGroup: "tbot/config/agent_net/group/CodeExecutionGroup.yaml"

start_node: "TBotGroup"

# 任务执行过程中的上下文信息（如返回值等），用于 group 之间的信息传递
context:
  - name: "task"
    type: "str"
  - name: "code"
    type: "list"
  - name: "variables"
    type: "list"
  - name: "completed_tasks"
    type: "list"
  - name: "error_message"
    type: "str"
