args:
  click_type: 单击
  click_event: 左键
  cursor_position: 中心
  x_offset: 0
  y_offset: 0
  name: ""
  operation_type: 3
  area: ""
  jpg: ""
  pre_delay: 0
  post_delay: 0
  continue_when_error: False