# 对外暴露的 id，用于将 group 引入 pipline
ref_id: "tbot_group"

# group 名称
name: "open document group"
# 对 group 的详细描述
description: "this group can open a word document"
# group 要完成的任务
task: ""

# group 内包含的 agent
agents:
  - PlanAgent: "tbot/config/agent/plan_agent.yaml"
  - ExecutionAgent: "tbot/config/agent/execution_agent.yaml"
  - ServiceAgent: "tbot/config/agent/service_agent.yaml"

# 信息流开始的 agent
start_agent: PlanAgent

# group 场景下的 prompt
prompts:
  - type: "inline"
    role: "start"
    content: |
      现在的用户需求为：{task}

      可以参考计划如下。

      {plans}

      请给出任务方案，不需要确认权限和服务支持情况。

# 初始化时需要的额外参数
initExtraParams:

# group 提供的工具
tools:

children:

# 其他参数
ifLeaf: True
ifService: False
runtimeRevisionNumber: 1
ifKnowledgeable: True
historyNumber: 0
energy: 0
