args:
  file_path: C:\\Users\\86188\\Desktop
  zip_cipher: ""
  target_path: C:\\Users\\86188\\Desktop
  select_algorithm: 最快
  zip_name: test
  pre_delay: 0
  post_delay: 0
  continue_when_error: False

rets:
  zip_path: zipped_path_name1
