# 对外暴露的 id，用于将 agent 引入 group
ref_id: "CodeExecutionAgent"

# agent 的名称
name: "CodeExecutionAgent"
# 对 agent 的详细描述
description: "可以进行 Excel 上的基础操作，如打开、保存、关闭表格，进行内容的输入、复制和粘贴等"
# agent 角色扮演相关？
role: ""
# agent 要执行的任务
task: ""
# agent 加载模式
load_type: "module"
# agent 类的位置
loadModule: "tbot.agent"
loadClass: "CodeExecutionAgent"

# 组内通信配置
# 其实好像不需要配置，因为目前实现的方式是 name + Exchange
communication:
  exchange: "WordOperationAgentExchange"
  queue: "WordOperationAgent"

# agent 是否需要与大模型进行交互
need_chat: True
model: "gpt-3.5-turbo"

init_extra_params:

# 执行上下文参数
params:
  - name: "code"
    type: "list"
  - name: "variables"
    type: "list"

# 执行上下文结果
results:

services:

# agent 的 prompt
prompts:

# agent 使用的工具
tools:
  - type: "VDB"
    name: "VDB1"

# agent 需要的输入结构
input_format: "format"

# agent 的下游 agent
children:
  - input_content_agent

# 其他的一些参数
ifLeaf: True
ifService: False
ifKnowledgeable: True
ifLearnable: False
runtimeRevisionNumber: 1
historyNumber: 0
energy: 0

